<?php
/**
 * Created by PhpStorm.
 * User: lucasweijers
 * Date: 16-08-17
 * Time: 14:58
 *
 * This asset will copy all fonts to the published directory.
 * It will be used on the front and backend of the application
 */
namespace plugins\starfish01\iconpicker\assets;

use craft\web\AssetBundle;

class sharedAsset extends AssetBundle
{
    public function init()
    {
        // define the path that your publishable resources live
        $this->sourcePath = '@storage/iconfonts';

        // try to find the file, if scss exists,
        if(file_exists(__DIR__ . '/../../../../../storage/iconfonts/css/fonts.css')) {

            // The css file is autogenerated in field/iconpicker.php, with the fonts that are available in the resources-shared folder
            $this->css = [
                'css/fonts.css',
            ];
        } elseif(file_exists(__DIR__ . '/../../../../../storage/iconfonts/css/fonts.css')) {
            // The css file is autogenerated in field/iconpicker.php, with the fonts that are available in the resources-shared folder
            $this->css = [
                'css/fonts.scss',
            ];
        }
        parent::init();
    }
}
